config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "outfits#index"
  resources :outfits do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, only: %i[index destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "owner", to: "outfits#change"
  get "owner/bookings", to: "bookings#owner"
  get "owner/outfits", to: "outfits#owner"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :outfit

  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :end_time, comparison: { greater_than: :start_time }
end

app/models/outfit.rb
class Outfit < ApplicationRecord
  CATEGORIES = %w[WEDDING FORMAL-OUTFIT PARTY-COSTUME].freeze
  belongs_to :user
  has_many :bookings, dependent: :destroy

  has_one_attached :photo

  validates :title, presence: true
  validates :description, presence: true
  validates :size, presence: true
  validates :price_per_day, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORIES }

  include PgSearch::Model

  pg_search_scope :search_by_title_description_category,
    against: %i[ title description category ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name is_owner avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name is_owner avatar])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^outfits$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_outfit, only: %i[new create]

  def index
    @bookings = Booking.all
    @user = current_user
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.outfit = @outfit
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path(@booking)
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  def owner
    @bookings = Booking.all
    @user = current_user
  end

  private

  def set_outfit
    @outfit = Outfit.find(params[:outfit_id])
  end

  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :total_price)
  end
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  before_action :set_outfit, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:query].present?
      @outfits = Outfit.search_by_title_description_category(params[:query])
    else
      @outfits = Outfit.all
    end
  end

  def show
    @booking = Booking.new
  end

  def new
    @outfit = Outfit.new
  end

  def create
    @outfit = Outfit.new(outfit_params)
    @outfit.user = current_user
    if @outfit.save
      redirect_to outfit_path(@outfit)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @outfit.update(outfit_params)
      redirect_to outfit_path(@outfit)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @outfit.destroy
    redirect_to outfits_path, status: :see_other
  end

  def owner
    @user = current_user
    @outfits = Outfit.all
  end

  private

  def outfit_params
    params.require(:outfit).permit(:title, :category, :description, :size, :price_per_day, :photo)
  end

  def set_outfit
    @outfit = Outfit.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1530103862676-de8c9debad1d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80);">
  <div class="container">
    <h1>My bookings</h1>
  </div>
</div>

<div class="container py-5">
  <div>
    <p>Note that if you cancel your booking, you will not be refunded.</p>
  </div>
  <div class="cards">
    <% @bookings.each do |booking| %>
      <% if @user.id == booking.user_id %>
        <div class="card">
          <% if booking.outfit.photo.attached? %>
          <%= cl_image_tag booking.outfit.photo.key, crop: :fill,  class:"cards-img"%>
          <div class="card-body">
            <h5 class="card-title"><%= booking.outfit.title %></h5>
            <div class="card-center">
              <p class="card-text">
                <i class="fa-regular fa-calendar"></i>
                 From : <%= booking.start_time %>
              </p>
                <p class="card-text">
                <i class="fa-solid fa-calendar"></i>
                   To : <%= booking.end_time %>
              </p>
              <p class="card-text">
                <i class="fa-solid fa-money-bill"></i>
                   Total Price :Rs  <%= booking.total_price %>
              </p>
              <%= link_to "Cancel Booking", booking_path(booking), class: "btn btn-outline-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this outfit?" } %>
            </div>
          </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/bookings/owner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1530103862676-de8c9debad1d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80);">
  <div class="container">
    <h1>My bookings' outfit</h1>
  </div>
</div>
<div class="container py-5">
  <div class="cards">
      <% @bookings.each do |booking| %>
        <% if @user.id == booking.outfit.user_id %>
          <div class="card">
            <% if booking.outfit.photo.attached? %>
            <%= cl_image_tag booking.outfit.photo.key, crop: :fill,  class:"cards-img"%>
            <div class="card-body">
              <h5 class="card-title"><%= booking.outfit.title %></h5>

              <div class="card-center">
                <p class="card-text">
                  <i class="fa-regular fa-calendar"></i>
                  From : <%= booking.start_time %>
                </p>
                  <p class="card-text">
                  <i class="fa-solid fa-calendar"></i>
                    To : <%= booking.end_time %>
                </p>
                <p class="card-text">
                  <i class="fa-solid fa-money-bill"></i>
                    Total Price :Rs  <%= booking.total_price %>
                </p>
                <%= link_to "Cancel Booking", owner_path(booking), class: "btn btn-outline-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this booking?" } %>
              </div>
            </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PartyOutfits</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Jost:wght@200;300;400;500;600&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Pinyon+Script&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Monsieur+La+Doulaise&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%# <%= notice %>
    <%# <%= alert %> 
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/outfits/_form.html.erb
<%= simple_form_for(outfit) do |f| %>
  <%= f.input :title %>
  <%= f.input :category, collection: [['SELECT-ONE', 'Please select a category'], ['WEDDING', 'Wedding'], ['FORMAL-OUTFIT', 'Formal outfit'], ['PARTY-COSTUME', 'Party costume']], label_method: :second, value_method: :first, include_blank: false %>
  <%= f.input :description %>
  <%= f.input :size %>
  <%= f.input :price_per_day %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/outfits/change.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1530103862676-de8c9debad1d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80);">
  <div class="container">
    <h1>YOUR BOOKING HAS BEEN CANCELED !</h1>
  </div>
</div>

<div class="container mt-5">
    <div class="row mt-5">
      <div class="col-12 m-auto">
        <div class="Sign-up-form mt-5">
          <%= link_to "Go 🏠", outfits_path, class: "btn btn-outline-warning btn-sm mt-4" %>
        </div>
    </div>
  </div>
</div>

app/views/outfits/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="outfit-form">
        <h1>Edit Outfit</h1>
        <div class="mt-3">
          <%= render 'form', outfit: @outfit %>
          <%= link_to "Go back", outfits_path, class: "btn btn-outline-dark btn-sm mt-4" %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="p-3"></div>

app/views/outfits/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1523521803700-b3bcaeab0150?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80);">
  <div class="container">
    <h1>Rent any kind of outfit for your event!</h1>
  </div>
  <div class="row justify-content-center">
    <div class="col-sm-8 my-5">
      <%= form_with url: outfits_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "What are you looking for?"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-burgendy" %>
    <% end %>
    </div>
  </div>
</div>

<div class="container py-5">
  <div class="cards">
    <% @outfits.each do |outfit| %>
      <%= link_to outfit_path(outfit), class:"text-decoration-none" do %>
      <div class="card">
        <% if outfit.photo.attached? %>
        <%= cl_image_tag outfit.photo.key, crop: :fill,  class:"cards-img"%>
        <div class="card-body">
          <h5 class="card-title"><%= outfit.title %></h5>

          <div class="card-center">
            <p class="card-text">
              <i class="fa-solid fa-ruler-vertical"></i>
              Size : <%= outfit.size %>
            </p>
            <p class="card-text">
              <i class="fa-solid fa-money-bill"></i>
              Rs <%= outfit.price_per_day %> /Day
            </p>
          </div>
        </div>
        <% end %>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/outfits/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="outfit-form">
        <h1>New Outfit</h1>
        <div class="mt-3">
          <%= render 'form', outfit: @outfit %>
          <%= link_to "Go back", outfits_path, class: "btn btn-outline-dark btn-sm mt-4" %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="p-3"></div>

app/views/outfits/owner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/313715/pexels-photo-313715.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1);">
  <div class="container">
    <h1>My outfits</h1>
  </div>
</div>

<div class="container py-5">
  <div class="cards">
    <% @outfits.each do |outfit| %>
      <div class="card">
      <%= link_to outfit_path(outfit), class:"text-decoration-none" do %>
        <% if @user.id == outfit.user_id %>
        <%= cl_image_tag outfit.photo.key, crop: :fill,  class:"cards-img"%>
        <div class="card-body">
          <h5 class="card-title"><%= outfit.title %></h5>
          <div class="card-center">
            <p class="card-text">
              <i class="fa-solid fa-ruler-vertical"></i>
              Size : <%= outfit.size %>
            </p>
            <p class="card-text">
              <i class="fa-solid fa-money-bill"></i>
              Rs <%= outfit.price_per_day %> /Day
            </p>
            <%= link_to "Remove Outfit", owner_outfits_path(@outfit), class: "btn btn-outline-danger", data: { turbo_method: :destroy, turbo_confirm: "Are you sure you want to delete this outfit?" } %>
          </div>
        </div>
        <% end %>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/outfits/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mb-5">
      <%= cl_image_tag @outfit.photo.key, height: 750, width: 500, crop: :fill %>
    </div>

    <div class="col-6">
      <div>
        <H2><%= @outfit.title %></H2>
        <div class="mt-2" id="show">
          <p>Category : <%= @outfit.category %></p>
        </div>
        <div class="mt-4">
          <p><%= @outfit.description %></p>
        </div>
        <div class="mt-2">
          <p>
            <i class="fa-solid fa-ruler-vertical"></i>
            Size : <%= @outfit.size %>
          </p>
        </div>
        <div class="mt-2">
          <p>
            <i class="fa-solid fa-money-bill"></i>
            Rs <%= @outfit.price_per_day %> /Day
          </p>
        </div>
        <div class="d-flex my-4">
          <% if @user = @outfit.user_id %>
            <%= link_to 'edit', edit_outfit_path, class: "button-arounder"%>
          <div class="ms-4"></div>
              <%= link_to "delete", outfit_path(@outfit), class: "button-arounder button-red", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this outfit?" } %>
            <% end %>
          </div>
        </div>
          <div class="col-4">
            <div class="flat-show-card">
              <h5>Book this outfit!</h5>
              <div data-controller="form-calculate" data-form-calculate-price-value=<%= @outfit.price_per_day %>>
                <%= simple_form_for([@outfit, @booking]) do |f| %>
                  <%= f.input :start_time , label: 'From :' , html5: true, input_html: {data: {form_calculate_target: "start", action: "change->form-calculate#test"}} %>
                  <%= f.input :end_time , label: 'To :' , html5: true, input_html: {data: {form_calculate_target: "end", action: "change->form-calculate#test"}} %>
                  <%= f.input :total_price, input_html: {data: {form_calculate_target: "totalprice"}}  %>
                  <%# <div>
                    <span>
                      Total Price :
                      <span id="target-value">
                      </span>
                    </span>
                  </div> %>
                  <%= f.submit data: {action: "submit->form-calculate#setValue"}, class: "btn btn-primary"%>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/outfits", class: "navbar-brand" do %>
      <%= image_tag "logo-color.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "My Bookings", "/bookings", class: "nav-link" %>
          </li>
          <% if current_user.is_owner? %>
            <li class="nav-item active">
            <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Owner</a>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Outfits", "/owner/outfits", class: "dropdown-item" %>
                <%= link_to "Bookings", "/owner/bookings", class: "dropdown-item" %>
                <%= link_to "Add an outfit", "/outfits/new", class: "dropdown-item" %>
              </div>
            </li>
            <% else %>
              <li class="nav-item active">
                <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Owner</a>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <%= link_to "Become an owner", "/owner", class: "dropdown-item" %>
                </div>
              </li>
            <% end %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, class: "avatar", alt: "dropdown menu"%>
            <% else %>
            <%= image_tag "https://w7.pngwing.com/pngs/931/209/png-transparent-computer-icons-symbol-avatar-logo-person-with-helmut-miscellaneous-black-silhouette.png", class: "avatar", alt: "dropdown menu" %>
            <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit Profile", "/users/edit", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>